server:
  port: 8081

#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    registry-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka


spring:
#  profiles:
#    active: prod

  datasource:
    url: jdbc:mysql://localhost:3306/hotel_management_system
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: USER-SERVICE

  config:
    import: configserver:http://localhost:8085


logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        type: trace
        stat: debug



URL:
  GET:
    RATINGS:
      BY:
        USERID: http://RATING-SERVICE/ratings/users/
    HOTELS:
      BY:
        HOTELID: http://HOTEL-SERVICE/hotels/

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
     web:
       exposure:
         include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        maxAttempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 0s
